package util;

public enum Event {
    SET_NICKNAME,
    ASK_NUM_PLAYERS,
    CHOOSE_NETWORK_PROTOCOL,
    CHOOSE_VIEW,
    START,
    START_YOUR_TURN,
    WAIT,
    ALL_CONNECTED,
    END,
    GAME_BOARD,
    GAME_BOOKSHELF,
    GAME_PLAYERS,
    GAME_CGC,
    GAME_PGC,
    GAME_SCORINGSTACK,
    GAME_PIT,
    GAME_STARTED;
}
